"""Turn PEM root certificates into src/certs.h.

Usage: python -I tools/make_certs.py out.h root1.pem [root2.pem ...]
Root certificates for PRIM (Google Trust Services) are at https://pki.goog/repository/
"""
import sys

HEADER = """// Root certificates used to verify https://prim.iledefrance-mobilites.fr
// (chain: leaf -> WE1 -> GTS Root R4). GTS Root R1 is kept as a fallback in
// case Google Trust Services switches the server to an RSA chain.
// Both roots are valid until 2036. Source: https://pki.goog/repository/
// Generated by tools/make_certs.py
#pragma once

static const char PRIM_ROOT_CA[] =
"""


def main():
    out, pems = sys.argv[1], sys.argv[2:]
    lines = []
    for path in pems:
        with open(path, encoding="ascii") as f:
            lines += [l.strip() for l in f if l.strip()]
    body = "\n".join('    "' + l + '\\n"' for l in lines)
    with open(out, "w", newline="\n", encoding="ascii") as f:
        f.write(HEADER + body + ";\n")


if __name__ == "__main__":
    main()
